package site.roomescape.springroomescaperevenge.mock;

import site.roomescape.springroomescaperevenge.common.exception.ResourceNotFoundException;
import site.roomescape.springroomescaperevenge.member.domain.Member;
import site.roomescape.springroomescaperevenge.member.service.port.MemberRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class FakeMemberRepository implements MemberRepository {

    private Long autoGeneratedId = 0L;
    public final List<Member> data = new ArrayList<>();

    @Override
    public List<Member> getAll() {
        return this.data;
    }

    @Override
    public Member getById(final Long memberId) {
        return data.stream()
                .filter(member -> member.getId().equals(memberId))
                .findFirst()
                .orElseThrow(() -> new ResourceNotFoundException("Member", memberId));
    }

    @Override
    public Member save(final Member member) {
        if (member.getId() == null || member.getId() == 0) {
            final Member createdMember = Member.builder()
                    .id(++autoGeneratedId)
                    .email(member.getEmail())
                    .password(member.getPassword())
                    .name(member.getName())
                    .role(member.getRole())
                    .build();
            data.add(createdMember);
            return createdMember;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), member.getId()));
            data.add(member);
            return member;
        }
    }
}
